Mappings:
  RegionMap:
    us-east-1:
      "64": "ami-0b0dcb5067f052a63"
    eu-west-3:
      "64": "ami-0f15e0a4c8d3ee5fe"
  Zones:
    us-east-1:
      "id": "us-east-1a"
    eu-west-3:
      "id": "eu-west-3b"

Parameters:
  SecurityGroupServerPort:
    Description: Server port
    Type: Number

Resources:
  # an EC2 instance
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !FindInMap [Zones, !Ref "AWS::Region", id]
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", 64]
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup

  # our EC2 security groups
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: !Ref SecurityGroupServerPort
          IpProtocol: tcp
          ToPort: !Ref SecurityGroupServerPort